<a href="https://colab.research.google.com/github/saran459/synent-task1-DataCleaningAndPreprocessing-SARAN.K/blob/main/synet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df.info()
df.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Passenger_ID      891 non-null    int64
 1   Survived          891 non-null    int64
 2   Passenger_Class   891 non-null    int64
 3   Passenger_Name    891 non-null    object
 4   Sex               891 non-null    int64
 5   Age               714 non-null    float64
 6   Siblings_Spouses  891 non-null    int64
 7   Parents_Children  891 non-null    int64
 8   Ticket_ID         891 non-null    object
 9   cost              891 non-null    float64
 10  Cabin_ID          204 non-null    object
 11  Port              889 non-null    object
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

,Passenger_ID,Survived,Passenger_Class,Passenger_Name,Sex,Age,Siblings_Spouses,Parents_Children,Ticket_ID,cost,Cabin_ID,Port
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
df.rename(columns={
    'PassengerId':'Passenger_ID',
    'Pclass':'Passenger_Class',
    'Name':'Passenger_Name',
    'SibSp':'Siblings_Spouses',
    'Parch':'Parents_Children',
    'Ticket':'Ticket_ID',
    'Fare':'cost',
    'Cabin':'Cabin_ID',
    'Embarked':'Port'
},inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Passenger_ID      891 non-null    int64
 1   Survived          891 non-null    int64
 2   Passenger_Class   891 non-null    int64
 3   Passenger_Name    891 non-null    object
 4   Sex               891 non-null    object
 5   Age               714 non-null    float64
 6   Siblings_Spouses  891 non-null    int64
 7   Parents_Children  891 non-null    int64
 8   Ticket_ID         891 non-null    object
 9   cost              891 non-null    float64
 10  Cabin_ID          204 non-null    object
 11  Port              889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

Passenger_ID          0
Survived              0
Passenger_Class       0
Passenger_Name        0
Sex                   0
Age                 177
Siblings_Spouses      0
Parents_Children      0
Ticket_ID             0
cost                  0
Cabin_ID            687
Port                  2
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Port'] = df['Port'].fillna(df['Port'].mode()[0])
df.isnull().sum()

Passenger_ID        0
Survived            0
Passenger_Class     0
Passenger_Name      0
Sex                 0
Age                 0
Siblings_Spouses    0
Parents_Children    0
Ticket_ID           0
cost                0
Port                0
dtype: int64

In [ ]:
df.to_csv('Titanic_Cleaned.csv', index=False)